// client/src/types/lucide-react.d.ts
declare module 'lucide-react' {
  import { FC, SVGProps, ForwardRefExoticComponent, RefAttributes } from 'react';

  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: string | number;
    color?: string;
    strokeWidth?: string | number;
    absoluteStrokeWidth?: boolean;
  }

  export type Icon = FC<IconProps>;
  export type LucideIcon = ForwardRefExoticComponent<Omit<IconProps, 'ref'> & RefAttributes<SVGSVGElement>>;

  // Default export
  const icons: { [key: string]: Icon };
  export default icons;

  // Named exports - alphabetically sorted
  export const Activity: Icon;
  export const AlertCircle: Icon;
  export const AlertOctagon: Icon;
  export const AlertTriangle: Icon;
  export const Anchor: Icon;
  export const ArrowDown: Icon;
  export const ArrowLeft: Icon;
  export const ArrowRight: Icon;
  export const ArrowUp: Icon;
  export const BarChart: Icon;
  export const BarChart3: Icon;
  export const Battery: Icon;
  export const Bell: Icon;
  export const BookOpen: Icon;
  export const Bot: Icon;
  export const Box: Icon;
  export const Brain: Icon;
  export const Bug: Icon;
  export const Calendar: Icon;
  export const Camera: Icon;
  export const Check: Icon;
  export const CheckCircle: Icon;
  export const ChevronDown: Icon;
  export const ChevronLeft: Icon;
  export const ChevronRight: Icon;
  export const ChevronUp: Icon;
  export const Circle: Icon;
  export const CircleAlert: Icon;
  export const Clock: Icon;
  export const Cloud: Icon;
  export const Code: Icon;
  export const Cog: Icon;
  export const Copy: Icon;
  export const Cpu: Icon;
  export const Database: Icon;
  export const Download: Icon;
  export const Edit: Icon;
  export const Edit2: Icon;
  export const Edit3: Icon;
  export const ExternalLink: Icon;
  export const Eye: Icon;
  export const EyeOff: Icon;
  export const File: Icon;
  export const FileText: Icon;
  export const Filter: Icon;
  export const Folder: Icon;
  export const FolderOpen: Icon;
  export const Gauge: Icon;
  export const GitBranch: Icon;
  export const Globe: Icon;
  export const Grid: Icon;
  export const Hash: Icon;
  export const Heart: Icon;
  export const HelpCircle: Icon;
  export const History: Icon;
  export const Home: Icon;
  export const Image: Icon;
  export const Info: Icon;
  export const Key: Icon;
  export const Keyboard: Icon;
  export const Layers: Icon;
  export const Layout: Icon;
  export const Link: Icon;
  export const Link2: Icon;
  export const List: Icon;
  export const Loader: Icon;
  export const Loader2: Icon;
  export const Lock: Icon;
  export const LogIn: Icon;
  export const LogOut: Icon;
  export const Mail: Icon;
  export const Map: Icon;
  export const MapPin: Icon;
  export const Maximize: Icon;
  export const Maximize2: Icon;
  export const MemoryStick: Icon;
  export const Menu: Icon;
  export const MessageCircle: Icon;
  export const MessageSquare: Icon;
  export const Mic: Icon;
  export const MicOff: Icon;
  export const Minimize: Icon;
  export const Minimize2: Icon;
  export const Minus: Icon;
  export const Monitor: Icon;
  export const Moon: Icon;
  export const MoreHorizontal: Icon;
  export const MoreVertical: Icon;
  export const MousePointer: Icon;
  export const MousePointer2: Icon;
  export const Move: Icon;
  export const Navigation: Icon;
  export const Network: Icon;
  export const Palette: Icon;
  export const Pause: Icon;
  export const PenTool: Icon;
  export const Play: Icon;
  export const Plus: Icon;
  export const Power: Icon;
  export const Puzzle: Icon;
  export const Redo: Icon;
  export const Redo2: Icon;
  export const RefreshCw: Icon;
  export const Rocket: Icon;
  export const RotateCcw: Icon;
  export const RotateCw: Icon;
  export const Route: Icon;
  export const Save: Icon;
  export const Search: Icon;
  export const Send: Icon;
  export const Server: Icon;
  export const Settings: Icon;
  export const Settings2: Icon;
  export const Share: Icon;
  export const Share2: Icon;
  export const Shield: Icon;
  export const SkipForward: Icon;
  export const Sliders: Icon;
  export const Smartphone: Icon;
  export const Sparkles: Icon;
  export const Square: Icon;
  export const Star: Icon;
  export const Sun: Icon;
  export const Tag: Icon;
  export const Target: Icon;
  export const Terminal: Icon;
  export const Trash: Icon;
  export const Trash2: Icon;
  export const TrendingDown: Icon;
  export const TrendingUp: Icon;
  export const Undo: Icon;
  export const Undo2: Icon;
  export const Unlock: Icon;
  export const Upload: Icon;
  export const User: Icon;
  export const Users: Icon;
  export const Video: Icon;
  export const Volume: Icon;
  export const Volume2: Icon;
  export const VolumeX: Icon;
  export const Wifi: Icon;
  export const WifiOff: Icon;
  export const X: Icon;
  export const XCircle: Icon;
  export const Zap: Icon;
  export const ZoomIn: Icon;
  export const ZoomOut: Icon;
}

// Declaration for deep imports from lucide-react
declare module 'lucide-react/dist/esm/icons/*' {
  import { Icon } from 'lucide-react';
  const icon: Icon;
  export default icon;
}