tunnel: logseqXR

ingress:
  - hostname: www.visionflow.info
    service: http://webxr-client:4000
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
      tcpKeepAlive: 10s
      keepAliveTimeout: 10m
      idleTimeout: 10m
      websocketIdleTimeout: 10m
      keepAliveConnections: 100
      httpHostHeader: www.visionflow.info
      proxyProtocol: false
    config:
      webSockets: true
      http2Origin: true
  - service: http_status:404

# Connection settings
protocol: http2
no-autoupdate: true

# Logging settings
loglevel: debug
