tunnel: your-tunnel-id
credentials-file: /etc/cloudflared/creds/credentials.json

ingress:
  - hostname: www.visionflow.info
    service: http://localhost:4000
  - service: http_status:404

# Optional logging configuration
logfile: /var/log/cloudflared.log
loglevel: info

# Connection settings
protocol: quic
no-autoupdate: true

# Logging settings
loglevel: debug
