version: '3.8'

services:
  visionflow:
    container_name: logseq_spring_thing_webxr
    build:
      context: .
      dockerfile: Dockerfile.production
    
    # CRITICAL: Must be on same network as multi-agent-container
    networks:
      - docker_ragflow
    
    # Ensure multi-agent container is ready with TCP server
    depends_on:
      multi-agent:
        condition: service_healthy
    
    environment:
      # TCP Connection Configuration
      - CLAUDE_FLOW_HOST=multi-agent-container
      - MCP_TCP_PORT=9500
      - MCP_TRANSPORT=tcp
      - MCP_RECONNECT_ATTEMPTS=3
      - MCP_RECONNECT_DELAY=1000
      - MCP_CONNECTION_TIMEOUT=30000
      
      # Logging
      - RUST_LOG=info,claude_flow=debug,tcp=debug
      
      # Other services
      - RAGFLOW_API_BASE_URL=http://ragflow-server:9380
      - RAGFLOW_AGENT_ID=${RAGFLOW_AGENT_ID}
      
      # Existing environment variables
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    
    ports:
      - "3001:3001"  # VisionFlow UI
      - "4000:4000"  # Internal API
    
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    
    # Health check that verifies TCP connection
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# CRITICAL: Use external network created by multi-agent-docker
networks:
  docker_ragflow:
    external: true