# Ontology Physics Configuration
# Maps OWL axioms to physics constraints

[kernel_parameters]
threads_per_block = 256
max_blocks = 1024
target_frame_time_ms = 2.0

[constraint_groups]
[constraint_groups.disjoint_classes]
enabled = true
kernel_name = "apply_disjoint_classes_kernel"
default_strength = 0.8
physics_type = "repulsion"

[constraint_groups.subclass_hierarchy]
enabled = true
kernel_name = "apply_subclass_hierarchy_kernel"
default_strength = 0.6
physics_type = "alignment"

[constraint_groups.sameas_colocate]
enabled = true
kernel_name = "apply_sameas_colocate_kernel"
default_strength = 0.9
physics_type = "attraction"

[constraint_groups.inverse_symmetry]
enabled = true
kernel_name = "apply_inverse_symmetry_kernel"
default_strength = 0.7
physics_type = "symmetry"

[constraint_groups.functional_cardinality]
enabled = true
kernel_name = "apply_functional_cardinality_kernel"
default_strength = 1.0
physics_type = "constraint"

[performance]
batch_size = 1000
memory_pool_size_mb = 512
max_concurrent_graphs = 4
