# Core visualization settings
[nodes]
base_color = "#c3ab6f"
base_size = 1.0
metalness = 0.3
opacity = 0.4
roughness = 0.35
size_range = [1.0, 5.0]
quality = "medium"
enable_instancing = false
enable_hologram = false
enable_metadata_shape = false
enable_metadata_visualization = false

[edges]
arrow_size = 0.15
base_width = 2.0
color = "#917f18"
enable_arrows = false
opacity = 0.6
width_range = [1.0, 3.0]

[physics]
attraction_strength = 0.015
bounds_size = 12.0
collision_radius = 0.25
damping = 0.88
enable_bounds = true
enabled = false
iterations = 500
max_velocity = 2.5
repulsion_strength = 1500.0
spring_strength = 0.018

[rendering]
ambient_light_intensity = 0.7
background_color = "#000000"
directional_light_intensity = 1.0
enable_ambient_occlusion = false
enable_antialiasing = true
enable_shadows = false
environment_intensity = 1.2

[animations]
enable_motion_blur = false
enable_node_animations = false
motion_blur_strength = 0.4
selection_wave_enabled = false
pulse_enabled = false
pulse_speed = 1.0
pulse_strength = 1.0
wave_speed = 1.0

[labels]
desktop_font_size = 48
enable_labels = true
text_color = "#FFFFFF"

[bloom]
edge_bloom_strength = 0.3
enabled = false
environment_bloom_strength = 0.5
node_bloom_strength = 0.2
radius = 0.5
strength = 1.8

[hologram]
ring_count = 3
ring_color = "#00ff00"
ring_opacity = 0.5
ring_sizes = [20.0, 25.0, 30.0]
ring_rotation_speed = 0.001
enable_buckminster = false
buckminster_scale = 15.0
buckminster_opacity = 0.3
enable_geodesic = false
geodesic_scale = 15.0
geodesic_opacity = 0.3
enable_triangle_sphere = false
triangle_sphere_scale = 15.0
triangle_sphere_opacity = 0.3
global_rotation_speed = 0.0005

# System settings
[network]
bind_address = "0.0.0.0"
domain = "localhost"
enable_http2 = false
enable_rate_limiting = true
enable_tls = false
max_request_size = 10485760
min_tls_version = ""
port = 3001
rate_limit_requests = 100
rate_limit_window = 60
tunnel_id = "dummy"
api_client_timeout = 30
enable_metrics = true
max_concurrent_requests = 5
max_retries = 3
metrics_port = 9090
retry_delay = 5

[websocket]
binary_chunk_size = 65536
binary_update_rate = 30
binary_message_version = 1
compression_enabled = true
compression_threshold = 1024
heartbeat_interval = 15000
heartbeat_timeout = 60000
max_connections = 1000
max_message_size = 100485760
reconnect_attempts = 3
reconnect_delay = 5000
update_rate = 90

[security]
allowed_origins = []
audit_log_path = "/app/logs/audit.log"
cookie_httponly = true
cookie_samesite = "Strict"
cookie_secure = true
csrf_token_timeout = 3600
enable_audit_logging = true
enable_request_validation = true
session_timeout = 3600

[debug]
enable_data_debug = false
enable_websocket_debug = false
enabled = false
log_binary_headers = false
log_full_json = false
log_level = "info"
log_format = "json"

# Server-only settings
[github]
rate_limit = true
version = "v3"
