# Unified Settings Configuration
# Clean, maintainable structure with multi-graph support

graphs:
  logseq:
    nodes:
      base_color: "#00ff88"
      metalness: 0.5
      opacity: 1.0
      roughness: 0.5
      node_size: 1.0
      quality: "high"
      enable_instancing: true
      enable_hologram: false
      enable_metadata_shape: true
      enable_metadata_visualisation: true
    
    edges:
      arrow_size: 0.5
      base_width: 0.1
      color: "#ffffff"
      enable_arrows: true
      opacity: 0.5
      width_range: [0.1, 1.0]
      quality: "high"
    
    labels:
      desktop_font_size: 14.0
      enable_labels: true
      text_color: "#ffffff"
      text_outline_color: "#000000"
      text_outline_width: 2.0
      text_resolution: 256
      text_padding: 4.0
      billboard_mode: "screen"
    
    physics:
      enabled: true
      iterations: 200  # Match original
      damping: 0.85  # Match original
      spring_strength: 0.02  # Match original - much gentler!
      repulsion_strength: 15.0  # Match original - less aggressive
      repulsion_distance: 50.0  # Match original
      attraction_strength: 0.05  # Match original
      max_velocity: 0.5  # Match original - slower
      collision_radius: 5.0  # Match original - smaller
      bounds_size: 150.0  # Match original - tighter bounds
      enable_bounds: true  # Match original
      mass_scale: 1.5  # Match original
      boundary_damping: 0.9  # Match original
  
  visionflow:
    nodes:
      base_color: "#ff8800"
      metalness: 0.7
      opacity: 0.9
      roughness: 0.3
      node_size: 1.5
      quality: "high"
      enable_instancing: true
      enable_hologram: true
      enable_metadata_shape: true
      enable_metadata_visualisation: true
    
    edges:
      arrow_size: 0.7
      base_width: 0.15
      color: "#ffaa00"
      enable_arrows: true
      opacity: 0.6
      width_range: [0.15, 1.5]
      quality: "high"
    
    labels:
      desktop_font_size: 16.0
      enable_labels: true
      text_color: "#ffaa00"
      text_outline_color: "#000000"
      text_outline_width: 2.5
      text_resolution: 256
      text_padding: 5.0
      billboard_mode: "screen"
    
    physics:
      enabled: true
      iterations: 150
      damping: 0.85
      spring_strength: 0.5
      repulsion_strength: 150.0
      repulsion_distance: 200.0
      attraction_strength: 0.002
      max_velocity: 15.0
      collision_radius: 60.0
      bounds_size: 3000.0
      enable_bounds: false
      mass_scale: 1.2
      boundary_damping: 0.6

rendering:
  ambient_light_intensity: 0.4
  background_color: "#000000"
  directional_light_intensity: 1.0
  enable_ambient_occlusion: false
  enable_antialiasing: true
  enable_shadows: false
  environment_intensity: 1.0

animations:
  enable_motion_blur: false
  enable_node_animations: true
  motion_blur_strength: 0.5
  selection_wave_enabled: true
  pulse_enabled: true
  pulse_speed: 1.0
  pulse_strength: 0.1
  wave_speed: 1.0

bloom:
  enabled: false
  strength: 1.0
  radius: 0.5
  node_bloom_strength: 1.0
  edge_bloom_strength: 1.0
  environment_bloom_strength: 1.0

websocket:
  update_rate: 30
  compression_enabled: false
  compression_threshold: 512
  reconnect_attempts: 5
  reconnect_delay: 1000
  binary_chunk_size: 2048
  heartbeat_interval: 10000
  max_message_size: 10485760

debug:
  enabled: false
  enable_physics_debug: false
  enable_websocket_debug: false
  log_level: "error"  # Match original - only log errors in production

network:
  bind_address: "0.0.0.0"
  port: 3001  # Changed from 4000 to avoid conflict with Nginx
  domain: "visionflow.info"  # Match original domain setting