visualization:
  nodes:
    base_color: '#495d7e'
    base_size: 8.0
    metalness: 0.6
    opacity: 0.9
    roughness: 0.4
    size_range:
    - 0.8
    - 2.0
    quality: high
    enable_instancing: true
    enable_hologram: true
    enable_metadata_shape: true
    enable_metadata_visualization: true
  edges:
    arrow_size: 0.8
    base_width: 0.8
    color: '#6e7c91'
    enable_arrows: true
    opacity: 0.4
    width_range:
    - 0.6
    - 1.6
  physics:
    attraction_strength: 0.012
    bounds_size: 5.0
    collision_radius: 0.3
    damping: 0.92
    enable_bounds: false
    enabled: true
    iterations: 600
    max_velocity: 2.0
    repulsion_strength: 1200.0
    spring_strength: 0.015
  rendering:
    ambient_light_intensity: 0.65
    background_color: '#1a1a2e'
    directional_light_intensity: 1.2
    enable_ambient_occlusion: false
    enable_antialiasing: false
    enable_shadows: false
    environment_intensity: 0.8
  animations:
    enable_motion_blur: false
    enable_node_animations: false
    motion_blur_strength: 0.35
    selection_wave_enabled: false
    pulse_enabled: false
    pulse_speed: 1.2
    pulse_strength: 1.1
    wave_speed: 0.8
  labels:
    desktop_font_size: 5
    enable_labels: true
    text_color: '#6087c3'
  bloom:
    edge_bloom_strength: 0.6
    enabled: true
    environment_bloom_strength: 0.3
    node_bloom_strength: 0.5
    radius: 1.0
    strength: 0.4
  hologram:
    ring_count: 1
    ring_color: '#455673'
    ring_opacity: 0.35
    ring_sizes:
    - 0.8
    - 1.2
    - 1.6
    - 2.0
    ring_rotation_speed: 0.08
    enable_buckminster: true
    buckminster_scale: 1.2
    buckminster_opacity: 0.3
    enable_geodesic: false
    geodesic_scale: 1.1
    geodesic_opacity: 0.3
    enable_triangle_sphere: false
    triangle_sphere_scale: 1.1
    triangle_sphere_opacity: 0.3
    global_rotation_speed: 0.06
system:
  network:
    bind_address: 0.0.0.0
    domain: localhost
    enable_http2: false
    enable_rate_limiting: true
    enable_tls: false
    max_request_size: 10485760
    min_tls_version: ''
    port: 3001
    rate_limit_requests: 100
    rate_limit_window: 60
    tunnel_id: dummy
    api_client_timeout: 30
    enable_metrics: true
    max_concurrent_requests: 5
    max_retries: 3
    metrics_port: 9090
    retry_delay: 5
  websocket:
    binary_chunk_size: 2048
    binary_update_rate: 60
    binary_message_version: 1
    compression_enabled: true
    compression_threshold: 512
    heartbeat_interval: 10000
    heartbeat_timeout: 30000
    max_connections: 1000
    max_message_size: 100485760
    reconnect_attempts: 3
    reconnect_delay: 3000
    update_rate: 90
  security:
    allowed_origins: []
    audit_log_path: /app/logs/audit.log
    cookie_httponly: true
    cookie_samesite: Strict
    cookie_secure: true
    csrf_token_timeout: 3600
    enable_audit_logging: true
    enable_request_validation: true
    session_timeout: 3600
  debug:
    enabled: false
    enable_data_debug: false
    enable_websocket_debug: false
    log_binary_headers: false
    log_full_json: false
    log_level: warn
    log_format: pretty
xr:
  mode: immersive-vr
  room_scale: true
  space_type: local-floor
  quality: high
  enable_hand_tracking: true
  hand_mesh_enabled: true
  hand_mesh_color: '#4287f5'
  hand_mesh_opacity: 0.3
  hand_point_size: 3.0
  hand_ray_enabled: true
  hand_ray_color: '#4287f5'
  hand_ray_width: 1.5
  gesture_smoothing: 0.7
  enable_haptics: true
  haptic_intensity: 0.3
  drag_threshold: 0.08
  pinch_threshold: 0.3
  rotation_threshold: 0.08
  interaction_radius: 0.15
  movement_speed: 0.08
  dead_zone: 0.12
  movement_axes:
    horizontal: 2
    vertical: 3
  enable_light_estimation: true
  enable_plane_detection: true
  enable_scene_understanding: true
  plane_color: '#4287f5'
  plane_opacity: 0.2
  plane_detection_distance: 3.0
  show_plane_overlay: true
  snap_to_floor: true
  enable_passthrough_portal: false
  passthrough_opacity: 0.8
  passthrough_brightness: 1.1
  passthrough_contrast: 1.2
  portal_size: 2.5
  portal_edge_color: '#4287f5'
  portal_edge_width: 0.5
ragflow:
  api_key: ''
  api_base_url: ''
  timeout: 30
  max_retries: 3
  chat_id: ''
perplexity:
  api_key: ''
  model: llama-3.1-sonar-small-128k-online
  api_url: ''
  max_tokens: 4096
  temperature: 0.5
  top_p: 0.9
  presence_penalty: 0.0
  frequency_penalty: 0.0
  timeout: 30
  rate_limit: 100
openai:
  api_key: ''
  base_url: ''
  timeout: 30
  rate_limit: 100
