# Minimal Settings - Only what's actually used
active_graph: logseq

graphs:
  logseq:
    physics:
      enabled: true
      iterations: 200
      damping: 0.85
      spring_strength: 0.02
      repulsion_strength: 15.0
      repulsion_distance: 50.0
      max_velocity: 0.5
      bounds_size: 150.0
      enable_bounds: true
      mass_scale: 1.5
      boundary_damping: 0.9
    
    nodes:
      base_color: "#66d9ef"
      size: 1.2
      opacity: 0.95
      metalness: 0.85
      roughness: 0.15
      enable_hologram: false
    
    edges:
      color: "#56b6c2"
      width: 0.5
      opacity: 0.25
      enable_arrows: false
      arrow_size: 0.02
    
    labels:
      enabled: true
      font_size: 0.5
      color: "#f8f8f2"
      outline_color: "#181c28"
      outline_width: 0.005
  
  visionflow:
    physics:
      enabled: true
      iterations: 150
      damping: 0.85
      spring_strength: 0.5
      repulsion_strength: 150.0
      repulsion_distance: 200.0
      max_velocity: 15.0
      bounds_size: 3000.0
      enable_bounds: false
      mass_scale: 1.2
      boundary_damping: 0.6
    
    nodes:
      base_color: "#ff8800"
      size: 1.5
      opacity: 0.9
      metalness: 0.7
      roughness: 0.3
      enable_hologram: true
    
    edges:
      color: "#ffaa00"
      width: 0.15
      opacity: 0.6
      enable_arrows: true
      arrow_size: 0.7
    
    labels:
      enabled: true
      font_size: 16.0
      color: "#ffaa00"
      outline_color: "#000000"
      outline_width: 2.5

rendering:
  background_color: "#0a0e1a"
  ambient_light: 1.2
  directional_light: 1.5
  enable_bloom: true
  bloom_strength: 1.5

network:
  port: 3001
  bind_address: "0.0.0.0"

websocket:
  update_rate: 30
  binary_chunk_size: 2048
  heartbeat_interval: 10000

debug: false