visualization:
  nodes:
    base_color: '#4287f5'
    base_size: 1.0
    metalness: 0.2
    opacity: 0.6
    roughness: 0.8
    size_range:
    - 0.5
    - 1.5
    quality: high
    enable_instancing: false
    enable_hologram: false
    enable_metadata_shape: true
    enable_metadata_visualization: true
  edges:
    arrow_size: 5.0
    base_width: 2.0
    color: '#6087c3'
    enable_arrows: true
    opacity: 0.9
    width_range:
    - 1.0
    - 3.0
  physics:
    attraction_strength: 0.02
    bounds_size: 200.0
    collision_radius: 0.5
    damping: 0.8
    enable_bounds: true
    enabled: true
    iterations: 200
    max_velocity: 0.5
    repulsion_strength: 800.0
    spring_strength: 0.025
  rendering:
    ambient_light_intensity: 0.4
    background_color: '#1a1a2e'
    directional_light_intensity: 0.6
    enable_ambient_occlusion: false
    enable_antialiasing: true
    enable_shadows: false
    environment_intensity: 0.3
  animations:
    enable_motion_blur: false
    enable_node_animations: false
    motion_blur_strength: 0.2
    selection_wave_enabled: false
    pulse_enabled: false
    pulse_speed: 0.8
    pulse_strength: 0.6
    wave_speed: 0.5
  labels:
    desktop_font_size: 14
    enable_labels: true
    text_color: '#ffffff'
    text_outline_color: '#000000'
    text_outline_width: 2
    text_resolution: 32
    text_padding: 4
    billboard_mode: 'camera'
  bloom:
    edge_bloom_strength: 0.8
    enabled: false
    environment_bloom_strength: 0.4
    node_bloom_strength: 1.2
    radius: 0.8
    strength: 0.7
  hologram:
    ring_count: 3
    ring_color: '#00ffff'
    ring_opacity: 0.4
    ring_sizes:
    - 0.9
    - 1.3
    - 1.7
    ring_rotation_speed: 0.05
    enable_buckminster: true
    buckminster_scale: 1.0
    buckminster_opacity: 0.35
    enable_geodesic: true
    geodesic_scale: 0.9
    geodesic_opacity: 0.3
    enable_triangle_sphere: true
    triangle_sphere_scale: 0.8
    triangle_sphere_opacity: 0.25
    global_rotation_speed: 0.03
system:
  network:
    bind_address: 0.0.0.0
    domain: "visionflow.info"
    enable_http2: false
    enable_rate_limiting: true
    enable_tls: false
    max_request_size: 10485760
    min_tls_version: ''
    port: 3001
    rate_limit_requests: 100
    rate_limit_window: 60
    tunnel_id: dummy
    api_client_timeout: 30
    enable_metrics: true
    max_concurrent_requests: 5
    max_retries: 3
    metrics_port: 9090
    retry_delay: 5
    allowed_origins: ["https://www.visionflow.info", "https://visionflow.info"]
  websocket:
    binary_chunk_size: 2048
    binary_update_rate: 60
    binary_message_version: 1
    compression_enabled: true
    compression_threshold: 512
    heartbeat_interval: 10000
    heartbeat_timeout: 30000
    max_connections: 1000
    max_message_size: 100485760
    reconnect_attempts: 3
    reconnect_delay: 3000
    update_rate: 90
  security:
    allowed_origins: ["https://www.visionflow.info", "https://visionflow.info"]
    audit_log_path: /app/logs/audit.log
    cookie_httponly: true
    cookie_samesite: Strict
    cookie_secure: true
    csrf_token_timeout: 3600
    enable_audit_logging: true
    enable_request_validation: true
    session_timeout: 3600
  debug:
    enabled: false
    enable_data_debug: false
    enable_websocket_debug: false
    log_binary_headers: false
    log_full_json: false
    log_level: info
    log_format: json
xr:
  mode: inline
  room_scale: 0.6
  space_type: local-floor
  quality: medium
  enable_hand_tracking: true
  hand_mesh_enabled: true
  hand_mesh_color: '#4287f5'
  hand_mesh_opacity: 0.3
  hand_point_size: 3.0
  hand_ray_enabled: true
  hand_ray_color: '#4287f5'
  hand_ray_width: 1.5
  gesture_smoothing: 0.7
  enable_haptics: true
  haptic_intensity: 0.3
  drag_threshold: 0.08
  pinch_threshold: 0.3
  rotation_threshold: 0.08
  interaction_radius: 0.15
  movement_speed: 0.08
  dead_zone: 0.12
  movement_axes:
    horizontal: 2
    vertical: 3
  enable_light_estimation: false
  enable_plane_detection: false
  enable_scene_understanding: false
  plane_color: '#4287f5'
  plane_opacity: 0.2
  plane_detection_distance: 3.0
  show_plane_overlay: false
  snap_to_floor: false
  enable_passthrough_portal: false
  passthrough_opacity: 0.8
  passthrough_brightness: 1.1
  passthrough_contrast: 1.2
  portal_size: 2.5
  portal_edge_color: '#4287f5'
  portal_edge_width: 0.5
ragflow:
  api_key: ''
  api_base_url: ''
  timeout: 30
  max_retries: 3
  chat_id: ''
perplexity:
  api_key: ''
  model: llama-3.1-sonar-small-128k-online
  api_url: ''
  max_tokens: 4096
  temperature: 0.5
  top_p: 0.9
  presence_penalty: 0.0
  frequency_penalty: 0.0
  timeout: 30
  rate_limit: 100
openai:
  api_key: ''
  base_url: ''
  timeout: 30
  rate_limit: 100
