#!/bin/bash

echo "======================================"
echo "Connection Diagnostic Information"
echo "======================================"
echo ""
echo "This container's network details:"
echo "---------------------------------"
echo "Container Name: $(hostname)"
echo "Container IP: $(hostname -I | awk '{print $1}')"
echo "Listening on: 0.0.0.0:9500"
echo ""
echo "Docker Network: docker_ragflow"
echo "Network Subnet: 172.18.0.0/16"
echo ""
echo "Known containers on network:"
echo "---------------------------"
echo "  172.18.0.10 - multi-agent-container (THIS CONTAINER)"
echo "  172.18.0.12 - logseq_spring_thing_webxr (VisionFlow)"
echo ""
echo "Connection Instructions for External System:"
echo "-------------------------------------------"
echo ""
echo "From the VisionFlow container, connect to:"
echo "  Host: 172.18.0.10"
echo "  Port: 9500"
echo "  Protocol: TCP with JSON-RPC 2.0"
echo ""
echo "Example test from VisionFlow container:"
echo "  echo '{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"initialize\",\"params\":{}}' | nc 172.18.0.10 9500"
echo ""
echo "Current Server Status:"
echo "---------------------"
if ps aux | grep -v grep | grep -q "node src/index.js"; then
    echo "✓ Server is RUNNING"
else
    echo "✗ Server is NOT running"
fi

if ss -tlnp 2>/dev/null | grep -q 9500; then
    echo "✓ Port 9500 is LISTENING"
else
    echo "✗ Port 9500 is NOT listening"
fi

echo ""
echo "Recent Connection Attempts:"
echo "--------------------------"
tail -n 20 logs/agent-control.log | grep -E "(connection|Connection)" || echo "No recent connections"
echo ""
echo "Troubleshooting:"
echo "---------------"
echo "1. Ensure VisionFlow is configured with:"
echo "   AGENT_CONTROL_URL=172.18.0.10:9500"
echo ""
echo "2. From VisionFlow container, test connectivity:"
echo "   ping 172.18.0.10"
echo "   telnet 172.18.0.10 9500"
echo ""
echo "3. Check VisionFlow logs for connection errors"
echo ""
echo "4. Verify both containers are on the same network:"
echo "   docker network inspect docker_ragflow"
echo ""