# This file allows us to acknowledge vulnerabilities in transitive dependencies
# that are difficult to upgrade without breaking changes

[advisories]
# Ignore the following advisories:
# RUSTSEC-2024-0421: 'idna' accepts Punycode labels that do not produce any non-ASCII when decoded
#   - This is a transitive dependency through nostr-sdk. Unable to upgrade without breaking changes.
# RUSTSEC-2025-0012: backoff is unmaintained
#   - Required by async-openai and our code doesn't use it directly. No viable alternatives.
# RUSTSEC-2024-0384: instant is unmaintained but required by multiple dependencies
# RUSTSEC-2024-0436: paste is unmaintained but required by simba/nalgebra
# RUSTSEC-2024-0320: yaml-rust is unmaintained but required by config
ignore = [
    "RUSTSEC-2024-0421",
    "RUSTSEC-2025-0012",
    "RUSTSEC-2024-0384",
    "RUSTSEC-2024-0436",
    "RUSTSEC-2024-0320"
]