[package]
name = "logseq-owl-extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
horned-owl = "0.11"
horned-functional = "0.4"
regex = "1.10"
walkdir = "2.4"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
