#!/usr/bin/env python3
"""Compare vendored ADR candidates without rewriting upstream history."""
from pathlib import Path
import json,hashlib,collections
base=Path(__file__).resolve().parents[1];w=base.parents[2]
j=json.loads((base/'evidence/adr-inventory.json').read_text());rows=[]
for r in j['records']:
 if r['repo']!='RuView' or not r['path'].startswith('vendor/ruvector/'):continue
 rel=r['path'][len('vendor/ruvector/'):];p=w/'ruvector'/rel
 state='standalone-path-absent'
 if p.is_file():state='byte-identical-copy' if hashlib.sha256(p.read_bytes()).hexdigest()==r['sha256'] else 'divergent-copy'
 rows.append({'vendor_path':r['path'],'standalone_path':rel,'comparison':state,'disposition':'vendored-reference; integration relevance and upstream lineage review remain open','sha256':r['sha256']})
counts=dict(collections.Counter(x['comparison'] for x in rows))
(base/'evidence/adr-lineage.json').write_text(json.dumps({'date':'2026-09-04','method':'path and SHA256 comparison of inventoried RuView/vendor/ruvector candidates with standalone ruvector checkout; no semantic equivalence claim','counts':counts,'records':rows},indent=2)+'\n')
lines=['# Vendored ADR lineage','', 'These records are retained in the estate inventory. They belong to the vendored RuVector reference tree within RuView; they are not automatically independent operator decisions. Byte equality establishes copy identity only, not correctness, relevance or completion. Divergent and absent counterparts require source-history review. No record is removed from scope by this comparison.','',f'Current comparison: **{len(rows)} candidates**; '+', '.join(f'{v} {k}' for k,v in counts.items())+'.','', 'Generated by [the collector](../evidence/adr-lineage.py); [machine-readable receipt](../evidence/adr-lineage.json).','', '| Vendored record | Standalone counterpart | Comparison |','|---|---|---|']
for x in rows:
 v=x['vendor_path'];s=x['standalone_path'];target=f'[{s}](<../../../../ruvector/{s}>)' if x['comparison']!='standalone-path-absent' else f'{s} (absent)'
 lines.append(f'| [{v}](<../../../../RuView/{v}>) | {target} | {x["comparison"]} |')
(base/'closeout/adr-lineage.md').write_text('\n'.join(lines)+'\n');print(counts)
