#!/usr/bin/env python3
"""Index local RuView decisions and existing estate-review links; no acceptance inference."""
from pathlib import Path
from collections import Counter
import json
import os
import re

HERE = Path(__file__).resolve().parent
REVIEW = HERE.parent
WORKSPACE = REVIEW.parents[2]
OUT = REVIEW / 'closeout/sensing-decisions.md'
records = json.loads((HERE / 'adr-inventory.json').read_text())['records']
records = sorted((r for r in records if r['repo'] == 'RuView' and r['kind'] == 'decision'
                  and (r['path'].startswith('docs/adr/') or
                       r['path'].startswith('rust-port/wifi-densepose-rs/docs/adr/'))),
                 key=lambda r: r['path'])
assert len({r['path'] for r in records}) == len(records)
counts = Counter(r['closeout'] for r in records)
lines = ['# RuView local decision review map', '',
         'Generated by [the collector](../evidence/sensing-decision-map.py) from the estate inventory and existing ADR links. This map covers local RuView decisions, including the Rust workspace pack; vendored RuVector decisions remain in the [upstream map](upstream-packs.md).', '',
         f"There are {len(records)} local decisions: {counts['evidence-backed-open']} with review extensions and {counts['evidence-review-required']} requiring dedicated review. An extension records bounded evidence, not semantic completion or runtime acceptance. Related source findings may exist for an unreviewed ADR without settling all of its decisions.", '',
         'Start with the [sensing assessment](../sensing-extension.md#reading-the-evidence). Resolve the actual consumed revision and deployment scope before turning a local upstream decision into an estate delivery requirement.', '',
         '| Decision | Review state | Existing assessment links |', '|---|---|---|']
receipt=[]
for r in records:
    source=WORKSPACE / r['repo'] / r['path']
    assert source.exists(), source
    links=[]
    for target in re.findall(r'\]\(<?([^\n)>]+)>?\)', source.read_text()):
        path, sep, anchor = target.partition('#')
        if not path or ':' in path: continue
        resolved=(source.parent / path).resolve()
        if resolved.parent != REVIEW or resolved.suffix != '.md': continue
        assert resolved.exists(), resolved
        link=os.path.relpath(resolved,OUT.parent)+(('#'+anchor) if sep else '')
        if link not in links: links.append(link)
    label=r['path'].removeprefix('docs/adr/')
    href=os.path.relpath(source,OUT.parent)
    rendered=', '.join(f'[assessment {i+1}]({link})' for i,link in enumerate(links)) or 'Dedicated assessment link not yet recorded'
    lines.append(f"| [{label}](<{href}>) | {r['closeout']} | {rendered} |")
    receipt.append({'path':r['path'],'review_state':r['closeout'],'assessment_links':links})
lines += ['', '## Review completion rule', '',
          'For each remaining decision, read all named modes, phases and acceptance claims; identify actual source and consumers; qualify historical statuses without erasing them; attach bounded evidence and a concrete closeout disposition. A filename, compatible helper or passing unrelated suite does not complete that work. Use the [assessment audit](assessment-requirements.md) to track completion separately from implementation.','']
OUT.write_text('\n'.join(lines))
(HERE/'sensing-decision-map.json').write_text(json.dumps({'scope':'Local RuView decision packs; excludes vendored decisions','counts':dict(counts),'records':receipt},indent=2)+'\n')
print(json.dumps({'local_decisions':len(records),'counts':dict(counts)}))
