#!/usr/bin/env python3
"""Route upstream decisions and capture consumed-source identities, without claiming adoption."""
from pathlib import Path
import json, hashlib, tomllib, collections, difflib
base=Path(__file__).resolve().parents[1]; w=base.parents[2]
inv=json.loads((base/'evidence/adr-inventory.json').read_text())
records=[]
for r in inv['records']:
    if r['repo'] not in ['ruvector','RuView'] or r['kind']!='decision': continue
    vendor=r['path'].startswith('vendor/ruvector/')
    relative=r['path'].removeprefix('vendor/ruvector/')
    family=str(Path(relative).parent)
    if r['repo']=='RuView' and not vendor: family='RuView/'+family
    records.append({'repo':r['repo'],'path':r['path'],'sha256':r['sha256'],'family':family,
                    'authority':'vendored reference' if vendor else 'local upstream decision',
                    'review':r['closeout'],'acceptance':'Source/consumer relevance and section-level disposition required; no estate adoption inferred'})
paths=['loom/Cargo.toml','RuView/rust-port/wifi-densepose-rs/Cargo.toml','RuView/rust-port/wifi-densepose-rs/Cargo.lock']
paths += ['RuView/rust-port/wifi-densepose-rs/crates/'+c+'/Cargo.toml' for c in ['wifi-densepose-ruvector','wifi-densepose-signal','wifi-densepose-mat']]
lock=tomllib.loads((w/paths[2]).read_text())
packages=[{k:p.get(k) for k in ['name','version','source','checksum']} for p in lock['package'] if p['name'].startswith('ruvector-')]
lineage=json.loads((base/'evidence/adr-lineage.json').read_text());diffs=[]
for r in lineage['records']:
    if r['comparison']!='divergent-copy':continue
    a=w/'RuView'/r['vendor_path'];b=w/'ruvector'/r['standalone_path']
    diffs.append({'vendor_path':r['vendor_path'],'standalone_path':r['standalone_path'],
                  'vendor_sha256':hashlib.sha256(a.read_bytes()).hexdigest(),
                  'standalone_sha256':hashlib.sha256(b.read_bytes()).hexdigest(),
                  'diff':''.join(difflib.unified_diff(a.read_text().splitlines(True),b.read_text().splitlines(True),fromfile=str(a),tofile=str(b),n=2))})
out={'date':'2026-09-05','scope':'Document/source identity and dependency declarations; no build, deployed-state or semantic-completion claim',
     'sources':{p:hashlib.sha256((w/p).read_bytes()).hexdigest() for p in paths},'locked_packages':packages,'divergent_records':diffs,'records':records}
(base/'evidence/upstream-pack-map.json').write_text(json.dumps(out,indent=2)+'\n')
lines=['# Upstream decision pack map','','Generated by [the collector](../evidence/upstream-pack-map.py). [Consumer and authority assessment](../upstream-decision-scope.md) explains the limits. Each record remains visible; grouping is a reading route, not semantic acceptance.','','| Family | Standalone/local | Vendored |','|---|---:|---:|']
families=sorted(set(r['family'] for r in records))
for f in families:
    rs=[r for r in records if r['family']==f]
    lines.append(f'| {f} | {sum(r["authority"]!="vendored reference" for r in rs)} | {sum(r["authority"]=="vendored reference" for r in rs)} |')
lines+=['','## Per-record review route','','| Record | Family | Authority | Current review |','|---|---|---|']
for r in records:
    label=r['repo']+'/'+r['path'];lines.append(f'| [{label}](<../../../../{label}>) | {r["family"]} | {r["authority"]} | {r["review"]} |')
(base/'closeout/upstream-packs.md').write_text('\n'.join(lines)+'\n')
print(json.dumps({'decision_records':len(records),'families':len(families),'divergent_pairs':len(diffs),'locked_ruvector_packages':len(packages)}))
