#!/usr/bin/env python3
"""Map explicit operative lineage mentions; never infer semantic supersession."""
from pathlib import Path
import hashlib,json,re
review=Path(__file__).resolve().parents[1];root=review.parents[1].parent/'project'
inv=json.loads((review/'evidence/adr-inventory.json').read_text())
history=[x for x in inv['records'] if x['repo']=='project' and x['kind']=='historical-decision']
operative=sorted((root/'docs/adr').glob('ADR-20*.md'));mentions={}
for p in operative:
 m=re.search(r'^lineage:\s*(.*)$',p.read_text(),re.M)
 if not m:continue
 for n in re.findall(r'\bADR-(\d{1,4})\b',m.group(1)):
  mentions.setdefault(int(n),[]).append({'path':str(p.relative_to(root)),'lineage':m.group(1)})
rows=[]
for h in sorted(history,key=lambda x:x['path']):
 p=root/h['path'];m=re.search(r'ADR-(\d+)',p.name);refs=mentions.get(int(m.group(1)),[]) if m else []
 rows.append({'path':h['path'],'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'explicit_lineage_mentions':refs,'disposition':'section-level-review-required' if refs else 'successor-or-retirement-review-required'})
d={'date':'2026-09-04','scope':'All inventory-classified VisionClaw historical candidates; exact numeric tokens in operative lineage fields only. Range expansion, aliases and semantic supersession are not inferred. Same-number cross-repository references require human interpretation.','historical_count':len(rows),'with_explicit_mention':sum(bool(x['explicit_lineage_mentions']) for x in rows),'rows':rows}
(review/'evidence/visionclaw-history-map.json').write_text(json.dumps(d,indent=2)+'\n')
out=['---','title: VisionClaw historical decision routing','status: in-progress','date: 2026-09-04','type: reference','---','','# VisionClaw historical decision routing','','Generated by [visionclaw-history-map.py](../evidence/visionclaw-history-map.py). This is a navigation map, not a supersession or completion certificate. Explicit lineage mentions can cover only one section of a compound ADR. Missing mentions are review work, not evidence that a decision was rejected. See the [section-level review](../historical-decision-reconciliation.md).','','| Historical record | Operative lineage mentions | Required disposition |','|---|---|---|']
for x in rows:
 p=Path(x['path']);link='[{}](<../../../../project/{}>)'.format(p.stem,x['path'])
 refs=', '.join('[{}](../../../../project/{})'.format(Path(y['path']).name.split('-')[0]+'-'+Path(y['path']).name.split('-')[1],y['path']) for y in x['explicit_lineage_mentions']) or 'None found in lineage fields'
 out.append('| '+link+' | '+refs+' | '+x['disposition']+' |')
(review/'closeout/visionclaw-history.md').write_text('\n'.join(out)+'\n')
print(json.dumps({k:d[k] for k in ['historical_count','with_explicit_mention']}))
